"""empty message

Revision ID: 3a3a97ad3247
Revises: 8685a4ba68b6
Create Date: 2016-10-06 13:46:57.867357

"""

# revision identifiers, used by Alembic.
revision = '3a3a97ad3247'
down_revision = '8685a4ba68b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alembic_version', sa.Column('version', sa.String(length=32), nullable=False), schema='sm_dev3')
    op.drop_column('alembic_version', 'version_num', schema='sm_dev3')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alembic_version', sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False), schema='sm_dev3')
    op.drop_column('alembic_version', 'version', schema='sm_dev3')
    ### end Alembic commands ###
