"""empty message

Revision ID: 4f33945b8bcd
Revises: 22f788327537
Create Date: 2016-07-12 16:51:12.744752

"""

# revision identifiers, used by Alembic.
revision = '4f33945b8bcd'
down_revision = '22f788327537'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraper', sa.Column('owner_id', sa.Integer(), nullable=True), schema='sm_dev')
    op.create_foreign_key(None, 'scraper', 'user', ['owner_id'], ['id'], source_schema='sm_dev', referent_schema='sm_dev')
    op.drop_column('scraper', 'owner', schema='sm_dev')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraper', sa.Column('owner', sa.VARCHAR(length=64), autoincrement=False, nullable=True), schema='sm_dev')
    op.drop_constraint(None, 'scraper', schema='sm_dev', type_='foreignkey')
    op.drop_column('scraper', 'owner_id', schema='sm_dev')
    ### end Alembic commands ###
