"""empty message

Revision ID: 601d25be44e4
Revises: 3a3a97ad3247
Create Date: 2016-10-06 13:47:24.181336

"""

# revision identifiers, used by Alembic.
revision = '601d25be44e4'
down_revision = '3a3a97ad3247'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
