"""empty message

Revision ID: 62417792ad3d
Revises: 8029b7f9ac6a
Create Date: 2016-07-12 19:56:24.674589

"""

# revision identifiers, used by Alembic.
revision = '62417792ad3d'
down_revision = '8029b7f9ac6a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scraper_added_by_fkey', 'scraper', schema='sm_dev', type_='foreignkey')
    op.drop_column('scraper', 'added_by', schema='sm_dev')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraper', sa.Column('added_by', sa.INTEGER(), autoincrement=False, nullable=True), schema='sm_dev')
    op.create_foreign_key('scraper_added_by_fkey', 'scraper', 'user', ['added_by'], ['id'], source_schema='sm_dev', referent_schema='sm_dev')
    ### end Alembic commands ###
