"""empty message

Revision ID: 8685a4ba68b6
Revises: 62417792ad3d
Create Date: 2016-10-06 13:41:26.482515

"""

# revision identifiers, used by Alembic.
revision = '8685a4ba68b6'
down_revision = '62417792ad3d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version', schema='sm_dev3')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    schema='sm_dev3'
    )
    ### end Alembic commands ###
