"""empty message

Revision ID: deb0b567b0bd
Revises: 601d25be44e4
Create Date: 2016-10-06 13:47:38.056314

"""

# revision identifiers, used by Alembic.
revision = 'deb0b567b0bd'
down_revision = '601d25be44e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
