"""empty message

Revision ID: fea77389a7b9
Revises: None
Create Date: 2016-10-27 23:43:54.252087

"""

# revision identifiers, used by Alembic.
revision = 'fea77389a7b9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('machine_name', sa.String(length=1024), nullable=True), schema='sm_dev')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'machine_name', schema='sm_dev')
    ### end Alembic commands ###
